### ISSUE TITLE
Please document what this is and what it does

### ISSUE THREAD

**Issue by probonopd** [tritest/AppIm#1]
Please document what this is and what it does, thank you.

Will this provide AppImages for download that could be included in the AppImageHub central directory of available AppImages?

**Comment by tritest** [comment]
Hi.

This is just playground to test different things out with ease. To not do that directly on official FreeCAD repository for AppImages. Results are more or less used for producing FreeCAD AppImages that are made available from FreeCAD GitHub releases page.
